services:
  backend:
    build:
      context: ./miel
      dockerfile: Dockerfile
    container_name: django_backend
#    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/app
      - app:/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_ALLOWED_HOSTS=*

  frontend:
    build:
      context: ./miel-front
      dockerfile: Dockerfile
    container_name: react_frontend
    volumes:
      - .:/app
      - app:/app/node_modules
    ports:
      - "3000:5173"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: miel_db

volumes:
  postgres_data:
  app: