# Generated by Django 5.1.4 on 2024-12-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создана')),
                ('current_workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы')),
                ('current_occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='Дата трудоустройства')),
                ('comment', models.CharField(max_length=300, verbose_name='Комментарии')),
                ('archived', models.BooleanField(blank=True, default=False, verbose_name='Архив')),
                ('synopsis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на резюме')),
                ('objects_card', models.IntegerField(blank=True, null=True, verbose_name='Объекты')),
                ('clients_card', models.IntegerField(blank=True, null=True, verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Карточку кандидата',
                'verbose_name_plural': 'Карточка кандидата',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предыдущий опыт')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Начало работы')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Окончание работы')),
            ],
            options={
                'verbose_name': 'Опыт',
                'verbose_name_plural': 'Опыт',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название офиса')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('link_to_admin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Связь с админом')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('contact_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Связь с кандидатом')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('gender', models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], max_length=50, null=True, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Персональную информацию',
                'verbose_name_plural': 'Персональная информация',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Квота на текущий месяц')),
                ('default', models.IntegerField(blank=True, null=True, verbose_name='Квота по дефолту')),
                ('used', models.IntegerField(blank=True, default=0, verbose_name='Использованная квота')),
                ('need', models.IntegerField(blank=True, default=0, verbose_name='Потребность по квоте')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Квоту',
                'verbose_name_plural': 'Квоты',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.candidatecard')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(blank=True, default=0, verbose_name='Прогресс')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.candidatecard')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.course')),
            ],
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='course',
            field=models.ManyToManyField(blank=True, through='showcase.CandidateCourse', to='showcase.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.experience', verbose_name='Опыт'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.candidatecard', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='showcase.candidatecard', verbose_name='Карточка кандидата')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашение',
            },
        ),
    ]
