# Generated by Django 5.1.4 on 2024-12-06 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCard',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('current_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(max_length=300)),
                ('favorite', models.BooleanField(blank=True, default=False)),
                ('archived', models.BooleanField(blank=True, default=False)),
                ('synopsis', models.CharField(blank=True, max_length=255, null=True)),
                ('objects_card', models.IntegerField(blank=True, null=True, verbose_name='Объекты')),
                ('clients_card', models.IntegerField(blank=True, null=True, verbose_name='Клиенты')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('contact_link', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('ma', 'мужской'), ('fe', 'женский')], max_length=2, null=True)),
                ('date_of_birth', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.candidatecard')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.course')),
            ],
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='course',
            field=models.ManyToManyField(to='showcase.candidatecourse'),
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.candidatecard')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.skill')),
            ],
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='skills',
            field=models.ManyToManyField(to='showcase.candidateskill'),
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.experience'),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('link_to_admin', models.CharField(blank=True, max_length=255, null=True)),
                ('quota', models.IntegerField(blank=True, null=True)),
                ('default_quota', models.IntegerField(blank=True, null=True)),
                ('user_quota', models.IntegerField(blank=True, null=True)),
                ('need_quota', models.IntegerField(blank=True, null=True)),
                ('superviser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='invitation_to_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.office'),
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='personal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.personalinfo'),
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.status'),
        ),
    ]
