# Generated by Django 5.1.4 on 2024-12-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecard',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecard',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='showcase.candidatecourse'),
        ),
        migrations.AlterField(
            model_name='candidatecard',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='showcase.candidateskill'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
